# 配置Tomcat端口号
server:
  port: 9999
# 配置Spring Boot项目名
spring:
  application:
    name: mall-server
# 配置Dubbo信息
  dubbo:
    application:
      name: mall-server
    protocol:      #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20880
    registry:     #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://localhost:2181
    scan: com.augustars.mall   #服务暴露与发现消费所在的package
# 配置使用JDK代理方式
  aop:
    proxy-target-class: true
# 配置数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: java
# 配置JPA信息
  jpa:
    show-sql: true
    open-in-view: true